name: Delete Closed Bot-Created PR Branches

on:
  schedule:
    # Run daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  delete-branches:
    name: Delete Closed PR Branches
    runs-on: ubuntu-latest
    env:
      GITHUB_BOT: github-actions[bot] # Define GITHUB_BOT at the job level

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          echo "Installing GitHub CLI..."
          sudo apt-get update
          sudo apt-get install -y gh jq

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Delete branches associated with closed PRs older than 30 days
      - name: Delete Closed PR Branches
        run: |
          gh pr list --state closed --json number,title,headRefName,closedAt,author,state | jq -c 'sort_by(.number)[]' | while read pr; do
            prNum=$(echo "$pr" | jq -r '.number')
            prTitle=$(echo "$pr" | jq -r '.title')
            echo "*****************************************************"
            echo "Processing PR #$prNum: $prTitle"
            branch=$(echo "$pr" | jq -r '.headRefName')
            branch_detail=$(gh api repos/:owner/:repo/branches/$branch 2> /dev/null || true)
            reqStatus=$(echo "$branch_detail" | jq -r '.status')
            if [[ "$reqStatus" == "404" ]]; then
              echo "- Branch does not exist, already deleted"
              continue
            fi

            closedAt=$(echo "$pr" | jq -r '.closedAt')
            authorIsBot=$(echo "$pr" | jq -r '.author.is_bot')

            author=$(echo "$branch_detail" | jq -r '.commit.author.login')

            # Check if the branch was created by a bot
            if [ "$authorIsBot" == "true" ]; then
              closedAtEpoch=$(date -d "$closedAt" +%s)
              nowEpoch=$(date +%s)
              age=$(( (nowEpoch - closedAtEpoch) / 86400 ))

              # Delete the branch if it is older than 30 days
              if [ $age -gt 30 ]; then
                echo "- Deleting branch: $branch (closed $age days ago by $author)"
                git push origin --delete "$branch" || echo "Failed to delete branch: $branch"
              else
                echo "- Skipping recent branch: $branch (closed $age days ago by $author)"
              fi
            else
              echo "- Skipping Non-Bot branch: $branch (created by $author)"
            fi
          done