name: Lint Files, Generate and Update Contributors

on:
  push: # Trigger on push events
    branches:
      - main # Only run on the main branch

env:
  GITHUB_BOT: github-actions[bot] # Define GITHUB_BOT at the workflow level

jobs:
  lint-and-update:
    name: Lint Files, Generate and Update Contributors
    runs-on: ubuntu-latest

    steps:
      # Exit early if the workflow was triggered by the bot
      - name: Check Actor
        run: |
          # Cannot use env.GITHUB_BOT in the 'if' condition for the job
          if [ "${{ github.actor }}" = "${{ env.GITHUB_BOT }}" ]; then
            echo "Push caused by GitHub Actions bot. Exiting."
            exit 0
          fi

      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install packages
      - name: Install Dependencies
        run: npm install -g all-contributors-cli markdownlint-cli prettier

      # Lint README.md
      - name: Lint README.md
        run: markdownlint --ignore-path ./.prettierignore --fix **/*.md
        continue-on-error: true # Continue even if linting fails

      # prettier
      - name: Prettier all files
        run: prettier --write .
        continue-on-error: true # Continue even if linting fails

      # Generate the updated README.md
      - name: Generate Contributors Section
        run: npx all-contributors-cli generate

      # Commit and push changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.GITHUB_BOT }}"
          git config --global user.email "${{ env.GITHUB_BOT }}@users.noreply.github.com"
          git config pull.rebase false
          branch=automated-linting-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated linting update'
          git add -A # Stages all changed files
          git commit -m "docs: linting & update contributors [skip ci]"  || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi
